# Generated by Django 4.2.4 on 2023-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(upload_to='img/')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('mother_name', models.CharField(max_length=120)),
                ('grandfather', models.CharField(max_length=120)),
                ('data_of_birth', models.DateTimeField()),
                ('born_city', models.CharField(max_length=60)),
            ],
        ),
    ]
